/**
 * Official-style photo & signature requirements for Indian forms.
 * Dimensions are in PIXELS (as used by most online application portals).
 * Always verify against the latest official notification — rules can change yearly.
 */

export const CATEGORIES = [
  'Govt Exams',
  'Entrance Exams',
  'Banking & Insurance',
  'Identity Documents',
];

export const PRESETS = [
  // ─── Govt Exams ───────────────────────────────────────────
  {
    id: 'upsc',
    name: 'UPSC (CSE / IFoS)',
    category: 'Govt Exams',
    icon: '🏛️',
    width: 350,
    height: 350,
    maxSizeKb: 300,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 300,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Recent passport-size colour photo, white/light background, full face visible',
    },
    signature: {
      width: 350,
      height: 150,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      description: 'Black ink on white paper, clear signature',
    },
  },
  {
    id: 'ssc',
    name: 'SSC (CGL / CHSL / MTS)',
    category: 'Govt Exams',
    icon: '📋',
    width: 413,
    height: 531,
    maxSizeKb: 50,
    photo: {
      width: 413,
      height: 531,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: '3.5 × 4.5 cm style, white background, front-facing',
    },
    signature: {
      width: 190,
      height: 95,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black/blue ink, clear on white',
    },
  },
  {
    id: 'railway',
    name: 'Railway (RRB NTPC / Group D)',
    category: 'Govt Exams',
    icon: '🚂',
    width: 413,
    height: 531,
    maxSizeKb: 50,
    photo: {
      width: 413,
      height: 531,
      minSize: 15,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white background, taken recently',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'nda',
    name: 'NDA / CDS',
    category: 'Govt Exams',
    icon: '🎖️',
    width: 350,
    height: 350,
    maxSizeKb: 300,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 300,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-size, white background, clear face',
    },
    signature: {
      width: 350,
      height: 150,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      description: 'Black ink on white',
    },
  },
  {
    id: 'capf',
    name: 'CAPF / CISF / CRPF',
    category: 'Govt Exams',
    icon: '🛡️',
    width: 350,
    height: 350,
    maxSizeKb: 300,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 300,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-size colour photo, light background',
    },
    signature: {
      width: 350,
      height: 150,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      description: 'Clear black ink signature',
    },
  },
  {
    id: 'afcat',
    name: 'AFCAT',
    category: 'Govt Exams',
    icon: '✈️',
    width: 350,
    height: 350,
    maxSizeKb: 100,
    photo: {
      width: 350,
      height: 350,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-size colour photo, white background',
    },
    signature: {
      width: 350,
      height: 150,
      minSize: 10,
      maxSize: 50,
      format: 'jpeg',
      description: 'Black ink on white paper',
    },
  },
  {
    id: 'ctet',
    name: 'CTET / State TET',
    category: 'Govt Exams',
    icon: '📚',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Recent photo, white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 4,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'state-psc',
    name: 'State PSC / PCS',
    category: 'Govt Exams',
    icon: '🏢',
    width: 350,
    height: 350,
    maxSizeKb: 200,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 200,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-size, white/light background (check state notice)',
    },
    signature: {
      width: 350,
      height: 150,
      minSize: 10,
      maxSize: 80,
      format: 'jpeg',
      description: 'Black ink on white paper',
    },
  },
  {
    id: 'police',
    name: 'Police / Constable',
    category: 'Govt Exams',
    icon: '👮',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 20,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white background, formal look',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'drdo-isro',
    name: 'DRDO / ISRO / BARC',
    category: 'Govt Exams',
    icon: '🚀',
    width: 350,
    height: 350,
    maxSizeKb: 100,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-size colour photo, white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 40,
      format: 'jpeg',
      description: 'Clear signature in black ink',
    },
  },
  {
    id: 'epfo-esic',
    name: 'EPFO / ESIC / SSC Stenographer',
    category: 'Govt Exams',
    icon: '📑',
    width: 413,
    height: 531,
    maxSizeKb: 50,
    photo: {
      width: 413,
      height: 531,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'White background, front-facing colour photo',
    },
    signature: {
      width: 190,
      height: 95,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },

  // ─── Banking & Insurance ──────────────────────────────────
  {
    id: 'ibps',
    name: 'IBPS (PO / Clerk / SO)',
    category: 'Banking & Insurance',
    icon: '🏦',
    width: 200,
    height: 230,
    maxSizeKb: 50,
    photo: {
      width: 200,
      height: 230,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white background, 200×230 px',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black ink, 140×60 px',
    },
  },
  {
    id: 'sbi',
    name: 'SBI (PO / Clerk / SO)',
    category: 'Banking & Insurance',
    icon: '🏦',
    width: 200,
    height: 230,
    maxSizeKb: 50,
    photo: {
      width: 200,
      height: 230,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo against white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'rbi',
    name: 'RBI Grade B / Assistant',
    category: 'Banking & Insurance',
    icon: '🏛️',
    width: 200,
    height: 230,
    maxSizeKb: 50,
    photo: {
      width: 200,
      height: 230,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Recent colour photo, white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black ink on white',
    },
  },
  {
    id: 'lic-niacl',
    name: 'LIC / NIACL / UIIC',
    category: 'Banking & Insurance',
    icon: '🛡️',
    width: 200,
    height: 230,
    maxSizeKb: 50,
    photo: {
      width: 200,
      height: 230,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-style colour photo, white bg',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'nabard',
    name: 'NABARD / SIDBI / Nainital Bank',
    category: 'Banking & Insurance',
    icon: '🌾',
    width: 200,
    height: 230,
    maxSizeKb: 50,
    photo: {
      width: 200,
      height: 230,
      minSize: 20,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 10,
      maxSize: 20,
      format: 'jpeg',
      description: 'Clear black ink signature',
    },
  },

  // ─── Entrance Exams ───────────────────────────────────────
  {
    id: 'neet',
    name: 'NEET (UG)',
    category: 'Entrance Exams',
    icon: '🩺',
    width: 413,
    height: 531,
    maxSizeKb: 200,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 200,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'White background, clear face, recent photo',
    },
    signature: {
      width: 413,
      height: 177,
      minSize: 4,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature on white',
    },
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    category: 'Entrance Exams',
    icon: '🔬',
    width: 413,
    height: 531,
    maxSizeKb: 200,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 200,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white background (NTA format)',
    },
    signature: {
      width: 413,
      height: 177,
      minSize: 4,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink, clear signature',
    },
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    category: 'Entrance Exams',
    icon: '⚗️',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Same style as JEE Main / NTA',
    },
    signature: {
      width: 413,
      height: 177,
      minSize: 4,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'cuet',
    name: 'CUET (UG / PG)',
    category: 'Entrance Exams',
    icon: '🎓',
    width: 413,
    height: 531,
    maxSizeKb: 200,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 200,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'White background, NTA-style photo',
    },
    signature: {
      width: 413,
      height: 177,
      minSize: 4,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink on white paper',
    },
  },
  {
    id: 'gate',
    name: 'GATE',
    category: 'Entrance Exams',
    icon: '⚙️',
    width: 480,
    height: 640,
    maxSizeKb: 200,
    photo: {
      width: 480,
      height: 640,
      minSize: 5,
      maxSize: 200,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white/light background',
    },
    signature: {
      width: 160,
      height: 70,
      minSize: 5,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'cat',
    name: 'CAT',
    category: 'Entrance Exams',
    icon: '📊',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Recent colour photo, white background',
    },
    signature: {
      width: 150,
      height: 50,
      minSize: 5,
      maxSize: 20,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'clat',
    name: 'CLAT / AILET',
    category: 'Entrance Exams',
    icon: '⚖️',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-style, white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 5,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'nift-nid',
    name: 'NIFT / NID / UCEED',
    category: 'Entrance Exams',
    icon: '🎨',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, plain white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 5,
      maxSize: 30,
      format: 'jpeg',
      description: 'Clear signature in black',
    },
  },
  {
    id: 'bitsat',
    name: 'BITSAT / VITEEE / SRMJEEE',
    category: 'Entrance Exams',
    icon: '💻',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Recent colour photo, white background',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 5,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },
  {
    id: 'aiims-ini',
    name: 'INI-CET / AIIMS PG',
    category: 'Entrance Exams',
    icon: '🏥',
    width: 413,
    height: 531,
    maxSizeKb: 100,
    photo: {
      width: 413,
      height: 531,
      minSize: 10,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'White background, clear face photo',
    },
    signature: {
      width: 140,
      height: 60,
      minSize: 5,
      maxSize: 30,
      format: 'jpeg',
      description: 'Black ink signature',
    },
  },

  // ─── Identity Documents ───────────────────────────────────
  {
    id: 'passport',
    name: 'Indian Passport',
    category: 'Identity Documents',
    icon: '🛂',
    width: 350,
    height: 350,
    maxSizeKb: 100,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: '2×2 inch style, white background, neutral expression',
    },
    signature: null,
  },
  {
    id: 'visa',
    name: 'Visa (Schengen / US style)',
    category: 'Identity Documents',
    icon: '✈️',
    width: 600,
    height: 600,
    maxSizeKb: 240,
    photo: {
      width: 600,
      height: 600,
      minSize: 20,
      maxSize: 240,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Square photo, white background (check embassy rules)',
    },
    signature: null,
  },
  {
    id: 'aadhaar',
    name: 'Aadhaar / e-Aadhaar',
    category: 'Identity Documents',
    icon: '🪪',
    width: 350,
    height: 350,
    maxSizeKb: 100,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Clear face photo, white/light background',
    },
    signature: null,
  },
  {
    id: 'pan',
    name: 'PAN Card',
    category: 'Identity Documents',
    icon: '💳',
    width: 213,
    height: 213,
    maxSizeKb: 50,
    photo: {
      width: 213,
      height: 213,
      minSize: 10,
      maxSize: 50,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Colour photo, white background',
    },
    signature: {
      width: 150,
      height: 50,
      minSize: 5,
      maxSize: 20,
      format: 'jpeg',
      description: 'Signature as on application',
    },
  },
  {
    id: 'driving-license',
    name: 'Driving Licence',
    category: 'Identity Documents',
    icon: '🚗',
    width: 350,
    height: 350,
    maxSizeKb: 100,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Passport-size colour photo, light background',
    },
    signature: null,
  },
  {
    id: 'voter-id',
    name: 'Voter ID (EPIC)',
    category: 'Identity Documents',
    icon: '🗳️',
    width: 350,
    height: 350,
    maxSizeKb: 100,
    photo: {
      width: 350,
      height: 350,
      minSize: 20,
      maxSize: 100,
      format: 'jpeg',
      bgColor: '#ffffff',
      description: 'Recent colour photo, white background',
    },
    signature: null,
  },
];

export const getPresetById = (id) => PRESETS.find((p) => p.id === id);

export const getPresetsByCategory = (category) =>
  PRESETS.filter((p) => p.category === category);

export default PRESETS;
